import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cura</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className='container'>

          <h1 className='mb-4 mt-5'>شركة كيورا للرعاية الصحية</h1>  
          <Link href='/doctors' className='btn btn-light border btn-lg'>
            شاهد جميع الأطباء من هنا
          </Link>
        </div>
      </main>
    </>
  )
}
